sudo: true
language: node_js
node_js:
- '7'
addons:
  ssh_known_hosts: 192.241.157.86
install:
- sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update
- sudo apt-get install yarn
- npm run install-all
after_success:
- yarn global add pm2
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then npm run deploy; fi;
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_install:
- openssl aes-256-cbc -K $encrypted_429e73a4feba_key -iv $encrypted_429e73a4feba_iv
  -in deploy_rsa.enc -out ./deploy_rsa -d
